"""empty message

Revision ID: 2a186a3a9f77
Revises: 815105647652
Create Date: 2019-05-15 14:19:23.324927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a186a3a9f77'
down_revision = '815105647652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'department', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'name')
    # ### end Alembic commands ###
