"""empty message

Revision ID: 815105647652
Revises: c84f559c4ed4
Create Date: 2019-05-15 14:18:54.456308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '815105647652'
down_revision = 'c84f559c4ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
