from .attribute_blueprint import attribute_blueprint
from .home_blueprint import home_blueprint
from .customer_blueprint import customer_blueprint
from .department_blueprint import department_blueprint